apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: frontend-shivam
data:
  BACKEND_URL: "http://35.223.85.48:5000/"

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: frontend-shivam
data:
  ELASTIC_USERNAME: "ZWxhc3RpYw=="
  ELASTIC_PASSWORD: "UT1XSDRUY1lXV2lUcmJ3RlNjZDk="
type: Opaque