apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: frontend-shivam
data:
  BACKEND_URL: "https://34.160.132.112/"

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: frontend-shivam
data:
  ELASTIC_USERNAME: "ZWxhc3RpYw=="
type: Opaque
