apiVersion: v1
kind: Service
metadata:
  name: frontend-shivam
  namespace: kubernetes-cluster-shivam
spec:
  type: LoadBalancer
  selector:
    app: frontend-shivam
  ports:
    - name: http
      port: 80
      targetPort: 80
